In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OrdinalEncoder , OneHotEncoder
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [ ]:
from google.colab import files
upload=files.upload()

Saving car_evaluation.csv to car_evaluation.csv

In [ ]:
car_evaluation_data = pd.read_csv("car_evaluation.csv", header=None)

In [ ]:
car_evaluation_data.shape

(1728, 7)

In [ ]:
car_evaluation_data.head()

       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [ ]:
column_names = ['Buying Price', 'Maintenance Cost', 'Doors', 'Persons', ' Luggage Boot Size', 'Safety', 'Class']

In [ ]:
car_evaluation_data.columns = column_names

In [ ]:
car_evaluation_data.head(5)

  Buying Price Maintenance Cost Doors Persons  Luggage Boot Size Safety  Class
0        vhigh            vhigh     2       2              small    low  unacc
1        vhigh            vhigh     2       2              small    med  unacc
2        vhigh            vhigh     2       2              small   high  unacc
3        vhigh            vhigh     2       2                med    low  unacc
4        vhigh            vhigh     2       2                med    med  unacc

In [ ]:
car_evaluation_data.isna().sum()

Buying Price          0
Maintenance Cost      0
Doors                 0
Persons               0
 Luggage Boot Size    0
Safety                0
Class                 0
dtype: int64

In [ ]:
X = car_evaluation_data.drop("Class", axis = 1)
y = car_evaluation_data["Class"]

In [ ]:
X.head()

  Buying Price Maintenance Cost Doors Persons  Luggage Boot Size Safety
0        vhigh            vhigh     2       2              small    low
1        vhigh            vhigh     2       2              small    med
2        vhigh            vhigh     2       2              small   high
3        vhigh            vhigh     2       2                med    low
4        vhigh            vhigh     2       2                med    med

In [ ]:
X.shape

(1728, 6)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25 , random_state = 42)

In [ ]:
X_test.shape

(432, 6)

In [ ]:
encoder = OrdinalEncoder(categories=[['low', 'med', 'high', 'vhigh'],
                                     ['low', 'med', 'high', 'vhigh'],
                                     ['2', '3', '4', '5more'],
                                     ['2', '4', 'more'],
                                     ['small', 'med', 'big'],
                                     ['low', 'med', 'high']])

In [ ]:
X_train = encoder.fit_transform(X_train)
X_test = encoder.fit_transform(X_test)

In [ ]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [ ]:
X_train.head()

     0    1    2    3    4    5
0  1.0  2.0  2.0  1.0  0.0  1.0
1  2.0  0.0  0.0  0.0  0.0  1.0
2  2.0  2.0  1.0  2.0  1.0  1.0
3  1.0  3.0  1.0  1.0  2.0  1.0
4  1.0  1.0  2.0  2.0  2.0  1.0

In [ ]:
column_names.remove('Class')

In [ ]:
X_train.columns = column_names
X_test.columns = column_names

In [ ]:
X_train.head()

   Buying Price  Maintenance Cost  Doors  Persons   Luggage Boot Size  Safety
0           1.0               2.0    2.0      1.0                 0.0     1.0
1           2.0               0.0    0.0      0.0                 0.0     1.0
2           2.0               2.0    1.0      2.0                 1.0     1.0
3           1.0               3.0    1.0      1.0                 2.0     1.0
4           1.0               1.0    2.0      2.0                 2.0     1.0

In [ ]:
X_test.head()

   Buying Price  Maintenance Cost  Doors  Persons   Luggage Boot Size  Safety
0           2.0               2.0    2.0      0.0                 1.0     2.0
1           1.0               0.0    0.0      1.0                 1.0     1.0
2           2.0               2.0    3.0      0.0                 2.0     1.0
3           0.0               2.0    3.0      1.0                 1.0     1.0
4           1.0               0.0    2.0      2.0                 1.0     0.0

In [ ]:
logistic_model = LogisticRegression(max_iter=100)

In [ ]:
logistic_model_results = cross_validate(logistic_model, X_train, y_train, cv= 5)

In [ ]:
print('Results:', logistic_model_results)

Results: {'fit_time': array([0.07672596, 0.05025816, 0.03977489, 0.03434801, 0.04546285]), 'score_time': array([0.00321245, 0.00292492, 0.00431037, 0.00292945, 0.0037508 ]), 'test_score': array([0.83846154, 0.77992278, 0.82239382, 0.83011583, 0.83783784])}

In [ ]:
print('Test Scores:', logistic_model_results['test_score'])

Test Scores: [0.83846154 0.77992278 0.82239382 0.83011583 0.83783784]

In [ ]:
print('Average Score:', format(logistic_model_results['test_score'].mean(), '.1%'))

Average Score: 82.2%

In [ ]:
logistic_model = LogisticRegression(max_iter=100)

In [ ]:
logistic_model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
logistic_model_preds = logistic_model.predict(X_test)

In [ ]:
print(format(accuracy_score(y_test, logistic_model_preds), ".1%"))

81.7%

In [ ]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn_model_results = cross_validate(knn_model, X_train, y_train, cv=5)

In [ ]:
print('Results:', knn_model_results)

Results: {'fit_time': array([0.00708699, 0.00561023, 0.00623274, 0.00653005, 0.00565362]), 'score_time': array([0.02897215, 0.02668238, 0.02929282, 0.02786946, 0.02953053]), 'test_score': array([0.93846154, 0.93822394, 0.92277992, 0.94208494, 0.93436293])}

In [ ]:
print('Test Scores:', knn_model_results['test_score'])

Test Scores: [0.93846154 0.93822394 0.92277992 0.94208494 0.93436293]

In [ ]:
print('Average Scores:', format(knn_model_results['test_score'].mean(), '.1%'))

In [ ]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
knn_model_preds = knn_model.predict(X_test)

In [ ]:
print(format(accuracy_score(y_test, knn_model_preds), ".1%"))

93.3%

In [ ]:
decision_tree_parameters = {'criterion': ['gini', 'entropy'], 'max_depth': [3, 4, 5, 6, 7, 8, 9, 10]}

In [ ]:
decision_tree_grid = GridSearchCV(DecisionTreeClassifier(), decision_tree_parameters, cv=5)

In [ ]:
decision_tree_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 5, 6, 7, 8, 9, 10]})

In [ ]:
print(decision_tree_grid.best_params_)

{'criterion': 'entropy', 'max_depth': 10}

In [ ]:
print(format(decision_tree_grid.best_score_, '.1%'))

97.7%

In [ ]:
decision_tree_model = DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state=42)

In [ ]:
decision_tree_model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state=42)

In [ ]:
decision_tree_model_preds = decision_tree_model.predict(X_test)

In [ ]:
print(format(accuracy_score(y_test, decision_tree_model_preds), ".1%"))

96.5%

In [ ]:
random_forest_parameters = {'criterion': ['gini', 'entropy'], 'n_estimators': [25, 50, 100, 150, 250, 500], 'max_depth': [3, 4, 5, 6, 7, 8, 9, 10]}

In [ ]:
random_forest_grid = GridSearchCV(RandomForestClassifier(random_state=42), random_forest_parameters, cv=5)

In [ ]:
random_forest_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 5, 6, 7, 8, 9, 10],
                         'n_estimators': [25, 50, 100, 150, 250, 500]})

In [ ]:
print(random_forest_grid.best_params_)

{'criterion': 'entropy', 'max_depth': 10, 'n_estimators': 150}

In [ ]:
print(format(random_forest_grid.best_score_, '.1%'))

98.1%

In [ ]:
random_forest_model = RandomForestClassifier(n_estimators=150, criterion='entropy', max_depth=10, random_state=42)

In [ ]:
random_forest_model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=150,
                       random_state=42)

In [ ]:
random_forest_model_preds = random_forest_model.predict(X_test)

In [ ]:
print(format(accuracy_score(y_test, random_forest_model_preds), ".1%"))

96.8%